import { basename } from "node:path";
import { getLanguageFromPath } from "@earendil-works/pi-coding-agent";

const LANGUAGE_EXTENSIONS: Record<string, string[]> = {
	ada: ["adb", "ads"],
	arduino: ["ino"],
	asciidoc: ["adoc"],
	autohotkey: ["ahk"],
	awk: ["awk"],
	bash: ["envrc", "bashrc", "zshrc", "ksh"],
	capnproto: ["capnp"],
	clojure: ["cljs", "cljc", "edn"],
	coffeescript: ["coffee"],
	cpp: ["hh", "hxx"],
	crystal: ["cr"],
	d: ["d"],
	dart: ["dart"],
	delphi: ["pas"],
	diff: ["diff", "patch"],
	dockerfile: ["containerfile"],
	dos: ["bat", "cmd"],
	elm: ["elm"],
	erb: ["erb"],
	erlang: ["hrl"],
	fortran: ["f90"],
	fsharp: ["fs", "fsx", "fsi"],
	gcode: ["gcode"],
	gherkin: ["feature"],
	glsl: ["glsl", "vert", "frag"],
	gradle: ["gradle"],
	groovy: ["groovy"],
	haml: ["haml"],
	handlebars: ["hbs", "handlebars"],
	haskell: ["lhs"],
	haxe: ["hx"],
	hy: ["hy"],
	ini: ["ini", "cfg"],
	json: ["jsonc", "ipynb", "geojson", "webmanifest"],
	julia: ["jl"],
	kotlin: ["kts"],
	latex: ["tex"],
	ldif: ["ldif"],
	lisp: ["lisp", "el"],
	livescript: ["ls"],
	llvm: ["ll"],
	makefile: ["mk", "mak"],
	markdown: ["mdx"],
	moonscript: ["moon"],
	nim: ["nim"],
	nix: ["nix"],
	nsis: ["nsi"],
	objectivec: ["mm"],
	ocaml: ["mli"],
	openscad: ["scad"],
	perl: ["pl", "pm"],
	powershell: ["psm1", "psd1"],
	properties: ["properties"],
	python: ["pyi"],
	qml: ["qml"],
	reasonml: ["re"],
	ruby: ["rake", "gemspec", "gemfile", "rakefile"],
	scala: ["sbt"],
	scheme: ["scm", "ss"],
	sml: ["sml"],
	stylus: ["styl"],
	tcl: ["tcl"],
	thrift: ["thrift"],
	twig: ["twig"],
	typescript: ["mts", "cts"],
	vala: ["vala"],
	vbnet: ["vb"],
	verilog: ["sv", "svh"],
	vhdl: ["vhd", "vhdl"],
	xml: ["svg", "xsd", "xsl", "plist"],
};

const EXTENSION_LANGUAGE = new Map(
	Object.entries(LANGUAGE_EXTENSIONS).flatMap(([language, extensions]) =>
		extensions.map((extension) => [extension, language] as const),
	),
);

export function languageFromPath(path: string): string | undefined {
	const name = basename(path);
	const extension = name.split(".").pop()?.toLowerCase() ?? "";
	return EXTENSION_LANGUAGE.get(extension) ?? getLanguageFromPath(name);
}
